version: '3.0'

services:

    # База данных PostgreSQL
    database:
        image: postgres:13
        container_name: 'converter_prod_db'
        ports:
            - 15435:5432 # для доступа с хост-машины
        environment:
            - 'POSTGRES_DB=converter_prod'
            - 'POSTGRES_USER=admin_prod'
            - 'POSTGRES_PASSWORD=456'
        volumes:
            - data-prod:/var/lib/postgresql/data
        networks:
            - net

    # Бэкенд (Spring Boot REST API на встроенном Tomcat-сервере)
    backend:
        image: alexz2/converter_back:1.0.0
        container_name: 'converter_prod_back'

        ports:
            - 8082:8082

        environment:
            - 'DATASOURCE_URL=jdbc:postgresql://database:5432/converter_prod'
            - 'DATASOURCE_USER=admin_prod'
            - 'DATASOURCE_PSWD=456'
        depends_on:
            - database
        networks:
            - net

    # AngularJS-фронтенд на сервере NGINX
    frontend:
        image: alexz2/converter_front:1.0.0
        container_name: 'converter_prod_front'
        ports:
            - 8099:80
        depends_on:
            - backend
        networks:
            - net

volumes:
    data-prod:

networks:
    net:
        driver: bridge
